# Generated by Django 4.1.2 on 2022-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
    ]
